apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend-nodeport
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30007
    protocol: TCP
    targetPort: 8000
  selector:
    app: longhorn-ui
