apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend-nodeport
spec:
  type: NodePort
  selector:
    app: longhorn-ui 
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
