---
agent:
  nodeSelector:
    kubernetes.io/arch: amd64
  image: "meldafrawi/jnlp-agent"
  tag: "20210913"
  privileged: true
  idleMinutes: 20
  resources:
    requests:
      cpu: "600m"
      memory: "1Gi"
    limits:
      cpu: "800m"
      memory: "2Gi"
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
