name: Automation-e2e
on:
  issues:
    types: [labeled]
jobs:
  backport:
    runs-on: ubuntu-latest
    if: contains(github.event.label.name, 'require/automation-e2e')
    steps:
      - name: Create Automation-e2e Test Issue
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ github.token }}
          title: |
            [TEST]${{ github.event.issue.title }}
          body: |
            adding/updating auto e2e test cases for ${{ github.event.issue.html_url }} if they can be automated
          assignees: ${{ join(github.event.issue.assignees.*.login, ', ') }}